language: python
sudo: false
python:
 - "2.7"
 - "3.4"
env:
  matrix:
    - DJANGO="django==1.7.10" REST="djangorestframework==2.4.8"
    - DJANGO="django==1.7.10" REST="djangorestframework==3.2.3"
    - DJANGO="django==1.8.4" REST="djangorestframework==2.4.8"
    - DJANGO="django==1.8.4" REST="djangorestframework==3.2.3"
    - DJANGO="django==1.8.4" REST="djangorestframework==3.2.3" LINT=1
  global:
    - PANDAS="pandas==0.16.2"
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $PANDAS
 - pip install flake8
script:
 - ./runtests.sh
