language: python
python:
 - "2.7"
 - "3.4"
env:
  matrix:
    - DJANGO="django==1.7.9" REST="djangorestframework==2.4.6"
    - DJANGO="django==1.7.9" REST="djangorestframework==3.1.1"
    - DJANGO="django==1.8.3" REST="djangorestframework==2.4.6"
    - DJANGO="django==1.8.3" REST="djangorestframework==3.1.3"
    - DJANGO="django==1.8.3" REST="djangorestframework==3.1.3" LINT=1
  global:
    - PANDAS="pandas==0.16.0"
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $PANDAS
 - pip install flake8
script:
 - ./runtests.sh
