language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  matrix:
    - DJANGO="django>=1.8, <1.10" REST="djangorestframework==3.3.3"
    - DJANGO="django==1.8, <1.10" REST="djangorestframework==3.3.3" LINT=1
    - DJANGO="django>=1.9, <1.10" REST="djangorestframework==3.3.3"
  global:
    - PANDAS="pandas>=0.18"
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $PANDAS
 - pip install flake8
script:
 - ./runtests.sh
