language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
env:
  matrix:
    - DJANGO="django==1.8.14"
    - DJANGO="django==1.9.9"
    - DJANGO="django==1.10"
    - DJANGO="django==1.10" LINT=1
  global:
    - REST="djangorestframework==3.4.6"
    - PANDAS="pandas>=0.18"
install:
 - pip install $DJANGO
 - pip install $REST
 - pip install $PANDAS
 - pip install matplotlib
 - pip install flake8
script:
 - ./runtests.sh
